USE musika;

CREATE TABLE IF NOT EXISTS users(
	UserId INTEGER NOT NULL AUTO_INCREMENT,
	username VARCHAR(254) NOT NULL,
	password VARCHAR(254) NOT NULL,
	email VARCHAR(254) NOT NULL,
	bio TEXT,
	
	PRIMARY KEY (UserId)
);

CREATE TABLE IF NOT EXISTS friend(
	UserId INTEGER NOT NULL,
	FriendId INTEGER NOT NULL,
	
	PRIMARY KEY (UserId, FriendId),
	FOREIGN KEY (UserId) REFERENCES users(UserId),
	FOREIGN KEY (FriendId) REFERENCES users(UserId)
);

CREATE TABLE IF NOT EXISTS genre(
	GID INTEGER NOT NULL AUTO_INCREMENT,
	type TEXT NOT NULL,
	description TEXT,
	
	PRIMARY KEY (GID)
);

CREATE TABLE IF NOT EXISTS media( 
	MID INTEGER NOT NULL AUTO_INCREMENT,
	type TEXT NOT NULL,
	description TEXT,
	
	PRIMARY KEY (MID)
);

CREATE TABLE IF NOT EXISTS album(
	albumID INTEGER NOT NULL AUTO_INCREMENT,
	name TEXT NOT NULL,
	year INTEGER,
	genre INTEGER,
	media INTEGER,
	
	PRIMARY KEY (AlbumID),
	FOREIGN KEY (genre) REFERENCES genre(GID),
	FOREIGN KEY (media) REFERENCES media(MID)
);
	

CREATE TABLE IF NOT EXISTS song(
	SID INTEGER NOT NULL AUTO_INCREMENT,
	title TEXT NOT NULL,
	description TEXT NOT NULL,
	AID INTEGER NOT NULL,
	genre INTEGER,
	media INTEGER,
	
	PRIMARY KEY (SID),
	FOREIGN KEY (AID) REFERENCES album(albumId),
	FOREIGN KEY (genre) REFERENCES genre(GID),
	FOREIGN KEY (media) REFERENCES media(MID)
);
